title: Minecraft Pi Whack-A-Block
hero_image: images/cover.png
description: Using the Minecraft Pi Edition API, you can create your own whack-a-mole clone.
original_url: https://www.raspberrypi.org/learning/minecraft-whac-a-block-game
theme: rpi-prototype
duration: 2
listed: false
ingredient: false
copyedit: false
interests: "games"
technologies: "python, minecraft, rpi"
steps:
  - title: Introduction
  - title: Whack-a-Block
  - title: Build a Whack-A-Block game board
  - title: Challenge
  - title: Switching a random block
  - title: Challenge
  - title: Getting the player ready
  - title: Turn the blocks on
  - title: Challenge
  - title: Whack blocks
  - title: Game over
  - title: What next?

