title: Minecraft Pi Whack-A-Block
hero_image: images/cover.png
subtitle: A Raspberry Pi whack-a-mole clone
description: Using the Minecraft Pi Edition API, you can create your own whack-a-mole clone.
published: false

steps:
  - title: Step one
    duration: 60
